environment   = "devl"
project_code  = "demo"
region        = "us-central1"
base_name     = "stream-table"
instance_name = "demo-bigtable-instance"
project_id    = "prj-15-cloud-bigtable-16748"
zone          = "us-central1-a"
